import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <div className="container mx-auto">
          <nav className=" text-white bg-sky-600 w-full h-18 mt-4  flex  justify-center items-center ">
            <Link  className=" bg-emerald-300 m-14 p-4 text-xl cursor-pointe hover:bg-emerald-400" href="/">Go To flex</Link>
            <Link  className=" bg-emerald-300 m-14 p-4 text-xl cursor-pointe hover:bg-emerald-400" href="/drid" >Go To Drid</Link>
            <Link  className=" bg-emerald-300 m-14 p-4 text-xl cursor-pointe hover:bg-emerald-400" href="/test1" >Go To test 1</Link>
            <Link  className=" bg-emerald-300 m-14 p-4 text-xl cursor-pointe hover:bg-emerald-400" href="/clind" >Go To clind</Link>
            <Link  className=" bg-emerald-300 m-14 p-4 text-xl cursor-pointe hover:bg-emerald-400" href="/post" >Go To posts</Link>
          </nav>
        {children}
        </div>
    </body>
    </html>
  );
}
